spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_students
    username: ActSpirits
    password: Scwm,dnyx0
    driver-class-name: com.mysql.cj.jdbc.Driver
# 需要注意,若你只引入了mybatisplus需要按以下配置
# 配置mapper映射
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#以下配置无法生效
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
server:
  port: 80
#    map-underscore-to-camel-case: true